apiVersion: v2
name: code-server-go
description: A Helm chart for deploying a Golang-based code server for internal use.
type: application
version: 1.0.2
appVersion: "v4.100.2"
icon: https://go.dev/blog/go-brand/Go-Logo/PNG/Go-Logo_Blue.png
keywords:
- go
- code