apiVersion: v1
kind: Service
metadata:
  name: {{ include "code-server-python.fullname" . }}
  labels:
    {{- include "code-server-python.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.http.port }}
      {{- if and (or (eq .Values.service.http.type "NodePort") (eq .Values.service.http.type "LoadBalancer")) .Values.service.http.nodePort }}
      nodePort: {{ .Values.service.http.nodePort }}
      {{- end }}
    - name: ssh
      protocol: TCP
      port: {{ .Values.service.ssh.port }}
      {{- if and (or (eq .Values.service.ssh.type "NodePort") (eq .Values.service.ssh.type "LoadBalancer")) .Values.service.ssh.nodePort }}
      nodePort: {{ .Values.service.ssh.nodePort }}
      {{- end }}
  selector:
    {{- include "code-server-python.selectorLabels" . | nindent 4 }}
